### ISSUE TITLE
Animal image data sets?

### ISSUE THREAD

**Issue by tianqig** [libphy/which_animal_2#1]
Thanks for your excellent work in use both image and sound. Do you have a report of combined performance?

Very interested in your project, wonder if you know any public image data set other than the cat/dog?
Or if possible to share your own?

**Comment by libphy** [comment]
Thanks for your interest! I haven't had a chance to work on it more- hopefully in the future I may try combining them somehow.. e.g. using videos. Are you looking for images of any objects or just animals? If you haven't already, I think either ImageNet, CIFAR10 or 100 might be a good option. They have images of many animal species as well as other objects.
